[Variables]

;Choose a custom font here

vFontFace="Segoe UI SemiLight"

;Chose a custom font size here

vFontSize=12

;Enter a custom font color here. Used in most text content places. It is entered in the format RRR,GGG,BBB,AAA

vFontColor=255,255,255,255

;Enter a custom accent color here. Used in various places. It is entered in the format RRR,GGG,BBB,AAA

vAccentColor=255,100,100,255

;Enter a custom tooltip background color here. Used as the solid color behind tootlips. It is entered 

;in the format RRR,GGG,BBB,AAA. Transparent colors are not *quite* finished yet.

vTooltipColor=44,44,44,255

;Enter media player choice here. Valid are: Spotify. Coming soon are: Google, iTunes, Apple, Winamp

vMediaPlayer = Spotify

;Choose how much the volume slider goes up on mouse wheel movement.

vVolumeIncrement=4

;Change the path to your steamname if required. Normally it is not.

vPreSteamNameUrl="http://steamcommunity.com/id/"

;Locale for weather parsing.

Locale=en_US

;Location Code for weather 

vWeatherCode=
