[sTooltip]
StringAlign=LeftTop
FontFace=Segoe UI SemiLight
AntiAlias=1
DynamicVariables=1
FontColor=#vLightFontColor#
SolidColor=#vTooltipColor#
FontSize=#vFontSize#
W=(#vSkinWidth#-(#vTooltipPadding# * 2))
X=0
Y=R
StringCase=Upper
padding=#vTooltipPadding#,#vTooltipPadding#,#vTooltipPadding#,#vTooltipPadding#

[sDescriptor]
padding=#vTooltipPadding#,#vTooltipPadding#,#vTooltipPadding#,0
FontColor=#vDarkFontColor#

[sMaintext]
padding=#vTooltipPadding#,0,#vTooltipPadding#,#vTooltipPadding#
FontSize=#vSubHeadingSize#
FontColor=#vAccentColor#

[sHeadingText]
padding=#vTooltipPadding#,#vTooltipPadding#,#vTooltipPadding#,0
FontSize=#vHeadingSize#
FontWeight=700

[sLargeHeadingText]
w=(#vSkinWidth# - #vTooltipPadding#)
padding=(#vTooltipPadding#/2),0,(#vTooltipPadding#/2),0
FontSize=#vLargeHeadingSize#
FontWeight=700
