[sTooltip]
StringAlign=LeftTop
FontFace=Segoe UI SemiLight
AntiAlias=1
DynamicVariables=1
FontColor=#vLightFontColor#
SolidColor=#vTooltipColor#
FontSize=#vFontSize#
W=(#vSkinWidth#-(#vTooltipPadding# * 2))
X=0
Y=R
StringCase=Upper

[sPaddingBottom]
padding=#vTooltipPadding#,0,#vTooltipPadding#,#vTooltipPadding#

[sPaddingTop]
padding=#vTooltipPadding#,#vTooltipPadding#,#vTooltipPadding#,0

[sPaddingAll]
padding=#vTooltipPadding#,#vTooltipPadding#,#vTooltipPadding#,#vTooltipPadding#

[sPaddingSides]
Padding=#vTooltipPadding#,0,#vTooltipPadding#,0

[sDescriptor]
FontColor=#vDarkFontColor#

[sMaintext]
FontSize=#vSubHeadingSize#
FontColor=#vAccentColor#

[sHeadingText]
FontSize=#vHeadingSize#
FontWeight=700

[sLargeHeadingText]
FontSize=#vLargeHeadingSize#
FontWeight=700
