[Variables]

vAccentColor=255,100,100,255
vTooltipAlpha=255
vTooltipColor=44,44,44,#vTooltipAlpha#
vIconWidth = 48
vIconHeight = 40
vOffset = 0
vSpacer = 48
vSpacerSmall = 24
vMediaPlayer = Spotify
vMediaPlayerColor = 30,215,96,255
vVolumeIncrement=4
vSteamColor=102,192,244,255
vNotifierHeight=2
vPreSteamNameUrl="http://steamcommunity.com/id/"
; UnitOfMeasure can be "f" (Fahrenheit / Imperial) or "m" (Celsius / Metric)
UnitOfMeasure=m
; Number of days to return in the feed.(1-6).
; The feed will always return the current conditions and the forecast for "Today"
; Then up to 5 additional forecast days. (Day 1 - Day 5)
DaysFeed=1
; Locale (language) to use in the feed.
; https://msdn.microsoft.com/en-us/goglobal/bb896001.aspx
; Note that Weather.com uses "_" underline instead of "-" dash in the codes.
Locale=en_US
vWeatherDegrees="  "
vWeatherCondition=" "
vWeatherIcon="temperature"
vMediaTrackProgress = 0

