[Variables]

vMediaTrackProgress=0
vSkinSteamWidth=400
vSkinMediaPlayerWidth=300
vSkinNetworkWidth=300
vAccentColor=255,100,100,255
vDarkFontColor=180,180,180,255
vTooltipColor=44,44,44,255
vIconWidth = 48
vIconHeight = 40
vOffset = 0
vSpacer = 48
vSpacerSmall = 24
vMediaPlayer = Spotify
vMediaPlayerColor = 30,215,96,255
vVolumeIncrement=4
vSteamColor=102,192,244,255
vNotifierHeight=2
vPreSteamNameUrl="http://steamcommunity.com/id/"
vWeatherDaysFeed=1
vWeatherLocale=en_US
vWeatherIcon="temperature"
vWeatherText="Please wait, Loading Weather..."
vFontFace="Segoe UI SemiLight"
vFontSize=12
vWWingUserDir = c:\users\%USERNAME%\wwing\
@Include2=#vWWingUserDir#variables.inc

